# Generated by Django 5.0.3 on 2024-03-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0003_userlog_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlog',
            old_name='text',
            new_name='information',
        ),
        migrations.AddField(
            model_name='userlog',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
