# Generated by Django 5.0.3 on 2024-03-26 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0006_userlog_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AssetManagerApp.space'),
        ),
    ]
