# Generated by Django 5.0.3 on 2024-03-29 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0009_userlog_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpaceMemberManagment',
            new_name='SpaceMemberManagement',
        ),
        migrations.AddField(
            model_name='space',
            name='code',
            field=models.CharField(default=None, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
