# Generated by Django 5.0.3 on 2024-03-29 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0011_alter_space_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='code',
        ),
        migrations.DeleteModel(
            name='SpaceMemberManagement',
        ),
    ]
