# Generated by Django 5.0.3 on 2024-03-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0012_remove_space_code_delete_spacemembermanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
