# Generated by Django 5.0.3 on 2024-03-29 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssetManagerApp', '0013_space_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
