# Generated by Django 5.0.3 on 2024-05-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0016_spaceroles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spaceroles",
            options={
                "permissions": [
                    ("can_edit_logs", "Can edit logs"),
                    ("can_delete_logs", "Can delete logs"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="userlog",
            options={"permissions": [("delete_log", "Can delete log")]},
        ),
        migrations.AlterUniqueTogether(
            name="spaceroles",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="spaceroles",
            name="role",
            field=models.CharField(
                choices=[("owner", "Owner"), ("member", "Member")], max_length=100
            ),
        ),
    ]
