# Generated by Django 5.0.3 on 2024-05-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AssetManagerApp",
            "0017_alter_spaceroles_options_alter_userlog_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="in_use",
            field=models.BooleanField(default=True),
        ),
    ]
