# Generated by Django 5.0.3 on 2024-05-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0021_userlog_switch_option"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlog",
            old_name="switch_option",
            new_name="in_use",
        ),
        migrations.AddField(
            model_name="userlog",
            name="last_changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_changed_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
