# Generated by Django 5.0.3 on 2024-05-26 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0022_rename_switch_option_userlog_in_use_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="last_changed_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
