# Generated by Django 5.0.3 on 2024-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0024_alter_userlog_last_changed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="last_changed_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
