# Generated by Django 5.0.3 on 2024-05-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0026_userlog_return_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlog",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
