# Generated by Django 5.0.3 on 2024-05-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0028_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="spaceroles",
            name="space",
        ),
        migrations.RemoveField(
            model_name="spaceroles",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="userlog",
            options={},
        ),
        migrations.RemoveField(
            model_name="space",
            name="code",
        ),
        migrations.RemoveField(
            model_name="space",
            name="members",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="email",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="in_use",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="last_changed_by",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="last_changed_date",
        ),
        migrations.RemoveField(
            model_name="userlog",
            name="return_by",
        ),
        migrations.AddField(
            model_name="space",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SpaceMemberManagment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AssetManagerApp.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="spaceRoles",
        ),
    ]
