# Generated by Django 5.0.3 on 2024-05-29 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0031_rename_descriptions_space_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
