# Generated by Django 5.0.3 on 2024-05-30 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0032_space_members"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlog",
            options={"permissions": [("delete_log", "Can delete log")]},
        ),
        migrations.RenameField(
            model_name="space",
            old_name="description",
            new_name="descriptions",
        ),
        migrations.RemoveField(
            model_name="space",
            name="pinned",
        ),
        migrations.AddField(
            model_name="userlog",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="userlog",
            name="in_use",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userlog",
            name="last_changed_by",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="userlog",
            name="last_changed_date",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="userlog",
            name="return_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="space",
            name="members",
            field=models.ManyToManyField(
                related_name="spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("members", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="spaceRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("member", "Member")],
                        max_length=100,
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AssetManagerApp.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_edit_logs", "Can edit logs"),
                    ("can_delete_logs", "Can delete logs"),
                ],
            },
        ),
        migrations.DeleteModel(
            name="SpaceMemberManagment",
        ),
    ]
