# Generated by Django 5.0.3 on 2024-05-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AssetManagerApp", "0033_alter_userlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
